name: Release PPA package

on:
  workflow_dispatch:
    inputs:
      url:
        description: The upstream package URL
        required: true
        type: string
      ppa:
        description: The PPA for the release
        required: true
        type: string

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:

      - name: Download upstream package
        run: curl -LOJ "${{ inputs.url }}"

      - name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ inputs.ppa }}

      - name: Upload source package
        uses: fragoi/debsign-action@main
        with:
          ppa: ${{ inputs.ppa }}
          gpg_key: ${{ secrets.SIGN_KEY }}
          gpg_pass: ${{ secrets.SIGN_PASS }}
          ssh_key: ${{ secrets.UPLOAD_PASS }}
          ssh_pass: ${{ secrets.UPLOAD_PASS }}
