name: Build and release PPA package

on:
  workflow_call:
    inputs:
      tag:
        description: The tag to build and release
        required: true
        type: string
      url:
        description: The upstream source package URL
        required: false
        type: string
      ppa:
        description: The PPA for the release
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - if: ${{ inputs.url }}
        name: Download upstream source
        run: curl -LOJ "${{ inputs.url }}"

      - name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ inputs.ppa }}

      - name: Upload source package
        uses: fragoi/debsign-action@main
        with:
          ppa: ${{ inputs.ppa }}
          gpg_key: ${{ secrets.SIGN_KEY }}
          gpg_pass: ${{ secrets.SIGN_PASS }}
          ssh_key: ${{ secrets.UPLOAD_PASS }}
          ssh_pass: ${{ secrets.UPLOAD_PASS }}
